# .dockerignore
node_modules
build
Dockerfile
.dockerignore
.git
.gitignore
*.md
tests/
logs/
.env
coverage

# Dockerfile
FROM node:18.18.0-alpine3.18 AS builder
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
RUN npm run build

FROM nginx:1.25.2-alpine3.18
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]